<?php

namespace App\Form;

use App\Entity\Campus;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class SearchSortieType extends AbstractType
{
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder
        ->add('campus',EntityType::class,[
            'class'        => Campus::class,
            'choice_label' => 'nom',
            'expanded'     => false,
            'disabled'     => false,
        ])
        ->add('nomSortie',TextType::class,[
            'label' =>'Le nom de la sortie contient : '
        ])
        ->add('debutInterval',DateType::class,[
            'widget' => 'choice',
        ])
        ->add('finInterval',DateType::class,[
            'widget' => 'choice',
        ])
    ;

    parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
}
}